# Generated by Django 5.1.4 on 2024-12-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='creativity_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='cultural_background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='emotional_response_tendency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='language_fluency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='primary_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='professional_background',
            field=models.TextField(blank=True, null=True),
        ),
    ]
